CREATE TABLE IF NOT EXISTS {{DATAWAREHOUSE_TABLE}} (
  LIKE {{DATASOURCE_TABLE}} INCLUDING ALL
);

CREATE UNIQUE INDEX IF NOT EXISTS {{UNIQUE_INDEX_NAME}}
  ON {{DATAWAREHOUSE_TABLE}} ({{UNIQUE_KEY}});

INSERT INTO {{DATAWAREHOUSE_TABLE}} ({{COLUMN_LIST}})
SELECT {{COLUMN_LIST}}
FROM {{DATASOURCE_TABLE}}
WHERE {{TS_COL}} >= now() - interval '{{WINDOW_MINUTES}} minutes'
ON CONFLICT ({{UNIQUE_KEY}}) DO UPDATE SET
  {{UPDATE_SET}};
