dag:
  dag_id: gold_star_schema
  schedule_cron: '*/5 * * * *'
  timezone: Asia/Jakarta
  owner: data-eng
  tags:
  - gold
  - clickhouse
  - star-schema
  max_active_tasks: 8
  default_window_minutes: 10
  enabled: true
pipelines:
- pipeline_id: dim_date
  enabled: true
  sql_path: sql/dim_date.sql
  window_minutes: 10
  params:
    target_table: gold.dim_date
- pipeline_id: dim_time
  enabled: true
  sql_path: sql/dim_time.sql
  window_minutes: 10
  params:
    target_table: gold.dim_time
- pipeline_id: dim_event
  enabled: true
  sql_path: sql/dim_event.sql
  window_minutes: 10
  params:
    target_table: gold.dim_event
- pipeline_id: dim_sensor
  enabled: true
  sql_path: sql/dim_sensor.sql
  window_minutes: 10
  params:
    target_table: gold.dim_sensor
- pipeline_id: dim_protocol
  enabled: true
  sql_path: sql/dim_protocol.sql
  window_minutes: 10
  params:
    target_table: gold.dim_protocol
- pipeline_id: dim_signature
  enabled: true
  sql_path: sql/dim_signature.sql
  window_minutes: 10
  params:
    target_table: gold.dim_signature
- pipeline_id: dim_tag
  enabled: true
  sql_path: sql/dim_tag.sql
  window_minutes: 10
  params:
    target_table: gold.dim_tag
- pipeline_id: dim_agent_scd2
  enabled: true
  sql_path: sql/dim_agent_scd2.sql
  window_minutes: 10
  params:
    target_table: gold.dim_agent
- pipeline_id: dim_host_scd2
  enabled: true
  sql_path: sql/dim_host_scd2.sql
  window_minutes: 10
  params:
    target_table: gold.dim_host
- pipeline_id: dim_rule_scd2
  enabled: true
  sql_path: sql/dim_rule_scd2.sql
  window_minutes: 10
  params:
    target_table: gold.dim_rule
- pipeline_id: fact_wazuh_events
  enabled: true
  sql_path: sql/fact_wazuh_events.sql
  window_minutes: 10
  depends_on:
  - dim_date
  - dim_time
  - dim_agent_scd2
  - dim_host_scd2
  - dim_rule_scd2
  - dim_event
  params:
    target_table: gold.fact_wazuh_events
- pipeline_id: fact_suricata_events
  enabled: true
  sql_path: sql/fact_suricata_events.sql
  window_minutes: 10
  depends_on:
  - dim_date
  - dim_time
  - dim_sensor
  - dim_signature
  - dim_protocol
  params:
    target_table: gold.fact_suricata_events
- pipeline_id: fact_zeek_events
  enabled: true
  sql_path: sql/fact_zeek_events.sql
  window_minutes: 10
  depends_on:
  - dim_date
  - dim_time
  - dim_sensor
  - dim_protocol
  - dim_event
  params:
    target_table: gold.fact_zeek_events
- pipeline_id: bridge_wazuh_event_tag
  enabled: true
  sql_path: sql/bridge_wazuh_event_tag.sql
  window_minutes: 10
  depends_on:
  - dim_tag
  - fact_wazuh_events
  params:
    target_table: gold.bridge_wazuh_event_tag
- pipeline_id: bridge_suricata_event_tag
  enabled: true
  sql_path: sql/bridge_suricata_event_tag.sql
  window_minutes: 10
  depends_on:
  - dim_tag
  - fact_suricata_events
  params:
    target_table: gold.bridge_suricata_event_tag
- pipeline_id: bridge_zeek_event_tag
  enabled: true
  sql_path: sql/bridge_zeek_event_tag.sql
  window_minutes: 10
  depends_on:
  - dim_tag
  - fact_zeek_events
  params:
    target_table: gold.bridge_zeek_event_tag
